### ISSUE TITLE
problem in traning

### ISSUE THREAD

**Issue by solin319** [xilaili/maskrcnn.mxnet#2]
I trained the model with "python maskrcnn_train_end2end.py --gpus 0 --prefix model/e2e  --end_epoch 10". Following is the error message. It seems like  a problem in reading mask files. But I can't know which file lead this break. Do you have any idea?

INFO:root:Epoch[0] Batch [13220]        Speed: 0.90 samples/sec Train-RPNAcc=0.922167,  RPNLogLoss=0.264778,       RPNL1Loss=1.411309,     RCNNAcc=0.804050,       RCNNLogLoss=1.091098,      RCNNL1Loss=2.086981,    MaskLoss=0.578198,

Traceback (most recent call last):
  File "maskrcnn_train_end2end.py", line 206, in <module>
    if __name__ == '__main__':
  File "maskrcnn_train_end2end.py", line 203, in main
    train_net(args, ctx, args.pretrained, args.pretrained_epoch, args.prefix, args.begin_epoch, args.end_epoch,
  File "maskrcnn_train_end2end.py", line 165, in train_net
    optimizer='sgd', optimizer_params=optimizer_params,
  File "/home/dlmxnet/lipengfei/maskrcnn.mxnet/rcnn/core/module.py", line 951, in fit
    eval_metric.reset()
  File "/home/dlmxnet/lipengfei/maskrcnn.mxnet/rcnn/core/loader.py", line 331, in next
    self.get_batch_parallel()
  File "/home/dlmxnet/lipengfei/maskrcnn.mxnet/rcnn/core/loader.py", line 446, in get_batch_parallel
    rst = self.parfetch(roidb)
  File "/home/dlmxnet/lipengfei/maskrcnn.mxnet/rcnn/core/loader.py", line 468, in parfetch
    gt_masks = get_gt_masks(roidb[0]['cache_seg_inst'], data['im_info'][0,:2].astype('int'))
  File "/home/dlmxnet/lipengfei/maskrcnn.mxnet/rcnn/mask/mask_transform.py", line 25, in get_gt_masks
    gt_masks = hkl.load(gt_mask_file)
  File "/home/dlmxnet/anaconda2/envs/mxnet-0.11-origin/lib/python2.7/site-packages/hickle.py", line 625, in load
    return py_container[0][0]
IndexError: list index out of range

**Comment by panyuetj** [comment]
I have the same problem
